#!/bin/sh
# REQUIRES FONT-AWESOME PACKAGE TO WORK PROPERLY

interval=0

### Load colors ###
. ~/dwm/scripts/bar_themes/onedark

### Date and clock ###
dte(){
        dte="$(date +"%a, %b %d %R")"
        icon="󱑆"
        printf "%s %s  " "$icon" "$dte"
}

### RAM ###
mem(){
#        mem="$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
	mem="$(free -h | awk '/^Mem/ { print $3"/"$2}' | sed s/i//g)"
        icon=""
        printf "%s %s" "$icon" "$mem"
}

### CPU ###
cpu(){
	cpu=$(grep -o "^[^ ]*" /proc/loadavg)
	icon=""
        printf " %s %s" "$icon" "$cpu%"
}

pkg_updates() {
        #updates=$({ timeout 20 checkupdates 2>/dev/null || true; } | wc -l) # arch
        updates=$({ timeout 20 aptitude search '~U' 2>/dev/null || true; } | wc -l) # debian
        icon=""
        printf "%s %s" "$icon" "$updates"
}

vol(){
        #vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
        vol="$(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
        icon=""
        printf "%s %s" "$icon" "$vol"
}

bat() {
        battery="$(cat /sys/class/power_supply/BAT0/capacity)"
        icon=""
        printf "%s %s" "$icon" "$battery%"
}

# Initial updates
vol

# Main loop
while true; do

  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "[$(cpu)][ $(mem)][ $updates][ $(bat)][ $(vol)][ $(dte)]"
done
