#!/bin/sh
# REQUIRES FONT-AWESOME PACKAGE TO WORK PROPERLY

interval=0

### Load colors ###
. ~/dwm/scripts/bar_themes/onedark

### Date and clock ###
dte(){
        dte="$(date +"%a, %b %d %R")"
        icon="󱑆"
        printf "^c$black^ ^b$darkblue^ %s ^c$black^ ^b$blue^ %s  " "$icon" "$dte"
}

### RAM ###
mem(){
        mem="$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
        icon=""
        printf " ^c$black^ ^b$blue^ %s ^c$blue^ ^b$black^ %s" "$icon" "$mem"
}

### CPU ###
cpu(){
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                icon=""
                printf "^c$black^ ^b$green^ %s ^c$white^ ^b$grey^ %s" "$icon" " $cpu%"
}

pkg_updates() {
        #updates=$({ timeout 20 checkupdates 2>/dev/null || true; } | wc -l) # arch
        updates=$({ timeout 20 aptitude search '~U' 2>/dev/null || true; } | wc -l) # debian
        icon=""
        printf "^c$black^ ^b$green^ %s ^c$green^ ^b$black^ %s" "$icon" "$updates"
}

vol(){
        #vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
        vol="$(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
        icon=""
        printf "^c$black^ ^b$white^ %s ^c$white^ ^b$black^ %s" "$icon" "$vol"
}

bat() {
        battery="$(cat /sys/class/power_supply/BAT0/capacity)"
        icon=""
        printf "^c$black^ ^b$red^ %s ^c$red^ ^b$black^ %s \\n" "$icon" "$battery%"
}

# Initial updates
vol

# Main loop
while true; do

  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "$(cpu) $(mem) $updates $(bat) $(vol) $(dte)"
done
