name: Check for bashisms

on:
  pull_request:
    branches: [main]
    paths:
      - scripts/**
  merge_group:
  workflow_dispatch:

jobs:
  check-bashisms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get the list of changed script files in the "scripts" folder
      - name: Get a list of changed script files
        id: get_sh_files
        run: |
          sh_files=$(find ./ -type f -name "*.sh")
          echo "Shell files: $sh_files"
          echo "sh_files=$sh_files" >> $GITHUB_ENV

      # Add a step to output the environment variable for debugging
      - name: Show found shell files
        run: "echo 'Found shell files: ${{ env.sh_files }}'"

      - name: Install devscripts
        if: ${{ env.sh_files != '' }}
        run: sudo apt-get update && sudo apt-get install devscripts

      - name: Check for bashisms
        if: ${{ env.sh_files != '' }}
        run: |
          for file in ${{ env.sh_files }}; do
              if [[ -f "$file" ]]; then
                  checkbashisms "$file"
              fi
          done
